name: Publish

on:
  push:
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x  # Currently needed for nuget-license; See https://github.com/sensslen/nuget-license/pull/110
            9.0.x
      - name: Install licensing information tool
        run: dotnet tool install --global nuget-license --version 3.0.14
      - name: Get Version
        uses: kzrnm/get-net-sdk-project-versions-action@v1.3.0
        id: get-version
        with:
          proj-path: src/Oneware.NetlistReaderFrontend/Oneware.NetlistReaderFrontend.csproj
      - name: Build
        run: dotnet build src/Oneware.NetlistReaderFrontend/Oneware.NetlistReaderFrontend.csproj -c Release -o publish
      - name: Generate licensing information
        run: nuget-license -i src/Oneware.NetlistReaderFrontend/Oneware.NetlistReaderFrontend.csproj -override src/Oneware.NetlistReaderFrontend/override-third-party.json -t -o Table -d src/Oneware.NetlistReaderFrontend/publish/THIRD-PARTY-LICENSES -fo src/Oneware.NetlistReaderFrontend/publish/THIRD-PARTY-NOTICE.txt
      - name: Compress
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: ../Oneware.NetlistReaderFrontend_${{steps.get-version.outputs.version}}_all.zip
          directory: ./publish
      - name: Debug
        run: ls
      - uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: "Oneware.NetlistReaderFrontend_${{steps.get-version.outputs.version}}_all.zip,./publish/compatibility.txt"
          tag: ${{steps.get-version.outputs.version}}
          allowUpdates: true
