# dotNET 8.0 is currently needed for nuget-license; See https://github.com/sensslen/nuget-license/pull/110

name: Publish

on:
  release:
    types: 
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x 
            9.0.x
      - name: Install licensing information tool
        run: dotnet tool install --global nuget-license --version 3.0.14
      - name: Get Version
        uses: kzrnm/get-net-sdk-project-versions-action@v1.3.0
        id: get-version
        with:
          proj-path: src/FEntwumS.NetlistViewer/FEntwumS.NetlistViewer.csproj
      - name: Build
        run: dotnet build src/FEntwumS.NetlistViewer/FEntwumS.NetlistViewer.csproj -c Release -o publish
      - name: Generate licensing information
        id: license
        run: nuget-license -i ./src/FEntwumS.NetlistViewer/FEntwumS.NetlistViewer.csproj -override ./src/FEntwumS.NetlistViewer/override-third-party.json -t -o Table -d ./publish/THIRD-PARTY-LICENSES -fo ./publish/THIRD-PARTY-NOTICE.txt
      - name: Copy font license
        id: font-license
        run: cp ./src/FEntwumS.NetlistViewer/Assets/Fonts/MartianMono-LICENSE.txt ./publish/THIRD-PARTY-LICENSES/Martian-Mono-License.txt
      - name: Compress
        if: steps.license.outcome == 'success'
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: ../FEntwumS.NetlistViewer_${{steps.get-version.outputs.version}}_all.zip
          directory: ./publish
      - name: Debug
        run: ls && ls -lshaR publish
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "FEntwumS.NetlistViewer_${{steps.get-version.outputs.version}}_all.zip,./publish/compatibility.txt"
          allowUpdates: true
          replacesArtifacts: false
          generateReleaseNotes: true
          omitBodyDuringUpdate: true
